import React,{useEffect,useState} from "react";
import ReactDOM from "react-dom/client";
import {BrowserRouter,useNavigate,useParams,Routes,Route,Link,Navigate,Outlet} from "react-router-dom";
import {createClient} from "@supabase/supabase-js";
import "./index.css";

const supabase=import.meta.env.VITE_SUPABASE_URL&&(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||import.meta.env.VITE_SUPABASE_ANON_KEY)?createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||import.meta.env.VITE_SUPABASE_ANON_KEY):null;
const STATUS=["Aberta","Em andamento","Aguardando cliente","Aguardando setor","Resolvida","Cancelada"];
const PRIORIDADES=["Baixa","Normal","Alta","Urgente"];
const cardStyle={padding:22};

function Home(){const nav=useNavigate();return <main className="app center"><div className="container" style={{textAlign:"center",maxWidth:800}}><div style={{fontSize:24,fontWeight:900,color:"#22d3ee",marginBottom:20}}>C+</div><h1 style={{fontSize:"clamp(42px,7vw,70px)",margin:"0 0 8px"}}>Conecta Mais 4.1</h1><p style={{fontSize:22,color:"#cbd5e1"}}>Central de atendimento inteligente</p><p className="muted">Uma entrada única para organizar solicitações, automatizar processos e gerar inteligência para a gestão.</p><button className="btn primary" style={{marginTop:25,fontSize:17}} onClick={()=>nav("/solicitacao")}>Abrir uma solicitação</button><div style={{marginTop:18}}><button className="btn ghost" onClick={()=>nav("/acompanhar")}>Acompanhar uma solicitação</button></div><div><button className="btn ghost" style={{marginTop:18}} onClick={()=>nav("/login")}>Acesso da equipe → Entrar</button></div></div></main>}

function Solicitacao(){const [sent,setSent]=useState(false),[protocol,setProtocol]=useState(""),[saving,setSaving]=useState(false),[error,setError]=useState("");const [f,setF]=useState({nome:"",canal:"Site",assunto:"",mensagem:"",categoria:""});const nav=useNavigate(),set=(k,v)=>setF(x=>({...x,[k]:v}));if(sent)return <main className="app center"><div className="container" style={{maxWidth:650,textAlign:"center"}}><div className="card" style={{padding:35}}><div style={{fontSize:48}}>✓</div><h1>Solicitação registrada</h1><p className="muted">Seu protocolo:</p><div style={{fontSize:36,fontWeight:900,color:"#22d3ee"}}>{protocol}</div><button className="btn primary" style={{marginTop:24}} onClick={()=>nav("/protocolo/"+protocol)}>Acompanhar solicitação</button></div></div></main>;return <main className="app" style={{padding:"45px 0"}}><div className="container" style={{maxWidth:760}}><button className="btn ghost" onClick={()=>nav("/")}>← Voltar</button><div className="card" style={{padding:30,marginTop:18}}><h1>Nova solicitação</h1><p className="muted">Preencha os dados. O Conecta Mais registra a solicitação diretamente no banco.</p><form className="grid" style={{marginTop:25}} onSubmit={async e=>{e.preventDefault();setError("");if(!supabase){setError("Supabase não configurado.");return}setSaving(true);const protocolo="CT-"+String(Date.now()).slice(-6);const {error:dbError}=await supabase.from("solicitacoes").insert([{protocolo,nome_cliente:f.nome,canal:f.canal,assunto:f.assunto,mensagem:f.mensagem,categoria:f.categoria||null,status:"Aberta",prioridade:"Normal"}]);setSaving(false);if(dbError){setError(dbError.message);return}setProtocol(protocolo);setSent(true)}}><div><label className="label">Nome do cliente</label><input className="input" required value={f.nome} onChange={e=>set("nome",e.target.value)}/></div><div className="grid grid2"><div><label className="label">Canal de entrada</label><select className="input" value={f.canal} onChange={e=>set("canal",e.target.value)}><option>Site</option><option>WhatsApp</option><option>E-mail</option><option>Telefone</option></select></div><div><label className="label">Categoria</label><input className="input" placeholder="Ex.: Financeiro" value={f.categoria} onChange={e=>set("categoria",e.target.value)}/></div></div><div><label className="label">Assunto</label><input className="input" required value={f.assunto} onChange={e=>set("assunto",e.target.value)}/></div><div><label className="label">Mensagem / descrição</label><textarea className="input" rows="7" required value={f.mensagem} onChange={e=>set("mensagem",e.target.value)}/></div>{error&&<div style={{color:"#fca5a5"}}>{error}</div>}<button className="btn primary" disabled={saving}>{saving?"Registrando...":"Enviar solicitação"}</button></form></div></div></main>}

function Acompanhar(){const nav=useNavigate();const [protocolo,setProtocolo]=useState("");const submit=e=>{e.preventDefault();const p=protocolo.trim().toUpperCase();if(p)nav("/protocolo/"+encodeURIComponent(p))};return <main className="app center"><div className="container" style={{maxWidth:600}}><div className="card" style={{padding:35}}><button className="btn ghost" onClick={()=>nav("/")}>← Voltar</button><h1 style={{marginTop:25}}>Acompanhar solicitação</h1><p className="muted">Informe o número do protocolo recebido ao registrar sua solicitação.</p><form className="grid" style={{marginTop:25}} onSubmit={submit}><div><label className="label">Número do protocolo</label><input className="input" required value={protocolo} onChange={e=>setProtocolo(e.target.value)} placeholder="Ex.: CT-616344" autoComplete="off"/></div><button className="btn primary" type="submit">Consultar solicitação</button></form></div></div></main>}

function Protocolo(){const {id}=useParams();const [dados,setDados]=useState(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");useEffect(()=>{async function buscar(){if(!supabase){setError("Sistema indisponível no momento.");setLoading(false);return}const protocolo=id?.trim();if(!protocolo){setError("Protocolo inválido.");setLoading(false);return}const {data,error}=await supabase.rpc("buscar_solicitacao",{p_protocolo:protocolo});if(error){setError(error.message)}else if(!data||data.length===0){setError("Não encontramos uma solicitação com este protocolo.")}else{setDados(data[0])}setLoading(false)}buscar()},[id]);return <main className="app center"><div className="container" style={{maxWidth:700}}><div className="card" style={{padding:35}}><p className="muted">Acompanhamento da solicitação</p><h1 style={{color:"#22d3ee",marginBottom:25}}>{id}</h1>{loading&&<p className="muted">Consultando solicitação...</p>}{error&&<div><div className="card" style={{padding:18,borderColor:"#7f1d1d",marginBottom:20}}><p style={{color:"#fca5a5",margin:0}}>{error}</p></div><Link className="btn ghost" to="/acompanhar">← Consultar outro protocolo</Link></div>}{dados&&<div style={{textAlign:"left"}}><div className="card" style={{padding:20,marginBottom:15,background:"#0b1e2d"}}><p className="muted">Cliente</p><strong>{dados.nome_cliente}</strong><p className="muted" style={{marginTop:15}}>Assunto</p><strong>{dados.assunto}</strong><p className="muted" style={{marginTop:15}}>Categoria</p><strong>{dados.categoria||"Não informada"}</strong></div><div className="card" style={{padding:20,marginBottom:15}}><p className="muted">Status</p><strong style={{fontSize:20}}>{dados.status}</strong><p className="muted" style={{marginTop:15}}>Prioridade</p><strong>{dados.prioridade}</strong></div><div className="card" style={{padding:20,marginBottom:15}}><p className="muted">Sua solicitação</p><p style={{whiteSpace:"pre-wrap",margin:0}}>{dados.mensagem}</p></div><div className="card" style={{padding:20,background:"#082b3a",borderColor:"#155e75"}}><p className="muted">Resposta / solução</p>{dados.resposta?<><p style={{whiteSpace:"pre-wrap",margin:0,lineHeight:1.6}}>{dados.resposta}</p>{dados.respondido_em&&<p className="muted" style={{marginTop:15,fontSize:13}}>Respondido em {new Date(dados.respondido_em).toLocaleString("pt-BR")}</p>}</>:<p className="muted" style={{margin:0}}>A equipe ainda não registrou uma resposta para esta solicitação.</p>}</div><div style={{marginTop:25,display:"flex",gap:10,flexWrap:"wrap"}}><Link className="btn ghost" to="/acompanhar">Consultar outro protocolo</Link><Link className="btn primary" to="/">← Início</Link></div></div>}</div></div></main>}
function Login(){const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(false);const nav=useNavigate();async function submit(e){e.preventDefault();setError("");if(!supabase){setError("Supabase não configurado. Verifique as variáveis da Vercel.");return}setLoading(true);const {error}=await supabase.auth.signInWithPassword({email,password});setLoading(false);if(error)setError(error.message);else nav("/dashboard")}return <main className="app center"><div className="container" style={{maxWidth:430}}><div className="card" style={{padding:30}}><h1>Acesso da equipe</h1><p className="muted">Área interna protegida.</p><form className="grid" onSubmit={submit} style={{marginTop:22}}><div><label className="label">E-mail</label><input className="input" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></div><div><label className="label">Senha</label><input className="input" type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></div>{error&&<div style={{color:"#fca5a5"}}>{error}</div>}<button className="btn primary" disabled={loading}>{loading?"Entrando...":"Entrar"}</button></form><button className="btn ghost" style={{width:"100%",marginTop:15}} onClick={()=>nav("/")}>← Área pública</button></div></div></main>}

function Protected(){const [loading,setLoading]=useState(true),[auth,setAuth]=useState(false);useEffect(()=>{if(!supabase){setLoading(false);return}supabase.auth.getSession().then(({data})=>{setAuth(!!data.session);setLoading(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setAuth(!!s));return()=>data.subscription.unsubscribe()},[]);if(loading)return <main className="app center">Verificando acesso...</main>;return auth?<Outlet/>:<Navigate to="/login" replace/>}

function Internal(){const nav=useNavigate();async function sair(){if(supabase)await supabase.auth.signOut();nav("/")}return <div className="app"><header style={{borderBottom:"1px solid #24384a",padding:"18px 0"}}><div className="container" style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:20}}><Link to="/dashboard" style={{textDecoration:"none",fontWeight:900,fontSize:20}}>C+ Conecta Mais</Link><nav style={{display:"flex",gap:15,flexWrap:"wrap"}}><Link to="/dashboard">Dashboard</Link><Link to="/atendimentos">Atendimentos</Link><Link to="/historico">Histórico</Link><Link to="/indicadores">Indicadores</Link><Link to="/configuracoes">Configurações</Link><button className="btn ghost" onClick={sair}>Sair</button></nav></div></header><div className="container" style={{padding:"30px 0"}}><Outlet/></div></div>}

function useSolicitacoes(){const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[updatedAt,setUpdatedAt]=useState(null);const load=async()=>{if(!supabase){setError("Supabase não configurado.");setLoading(false);return}setLoading(true);const {data,error}=await supabase.from("solicitacoes").select("*").eq("excluida",false).order("created_at",{ascending:false});if(error)setError(error.message);else{setRows(data||[]);setUpdatedAt(new Date())}setLoading(false)};useEffect(()=>{load()},[]);return {rows,loading,error,updatedAt,reload:load}};

function Dashboard(){
const {rows,loading,error,updatedAt,reload}=useSolicitacoes();

const pendentes=rows.filter(r=>r.status!=="Resolvida"&&r.status!=="Cancelada");
const abertos=rows.filter(r=>r.status==="Aberta");
const andamento=rows.filter(r=>r.status==="Em andamento");
const resolvidas=rows.filter(r=>r.status==="Resolvida");
const canceladas=rows.filter(r=>r.status==="Cancelada");
const urgentes=rows.filter(r=>r.prioridade==="Urgente");

const canais=["Site","WhatsApp","E-mail","Telefone"];
const statusDashboard=["Aberta","Em andamento","Aguardando cliente","Aguardando setor","Resolvida","Cancelada"];
const categorias=[...new Set(rows.map(r=>r.categoria).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"pt-BR"));
const responsaveis=[...new Set(rows.map(r=>r.responsavel).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"pt-BR"));
const recentes=rows.slice(0,6);

const percentual=(valor,total)=>total?Math.round((valor/total)*100):0;
const maior=(lista)=>Math.max(1,...lista.map(x=>x[1]));

const metricas=[
  ["Solicitações",rows.length,"Todas as solicitações ativas no sistema"],
  ["Pendentes",pendentes.length,"Ainda precisam de atendimento"],
  ["Em andamento",andamento.length,"Atendimentos em execução"],
  ["Urgentes",urgentes.length,"Prioridade que exige atenção"],
  ["Resolvidas",resolvidas.length,"Atendimentos concluídos"],
  ["Canceladas",canceladas.length,"Atendimentos cancelados"]
];

return <section>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:16,flexWrap:"wrap"}}>
  <div>
    <h1>Dashboard</h1>
    <p className="muted">Visão operacional do Conecta Mais 4.1.</p>
  </div>
  <div style={{display:"flex",alignItems:"center",gap:10}}>
    <Link className="btn primary" to="/atendimentos">Abrir fila de atendimento</Link>
    <button className="btn ghost" onClick={reload}>{loading?"Atualizando...":"Atualizar"}</button>
  </div>
</div>

{updatedAt&&<div className="muted" style={{fontSize:12,marginTop:8}}>Última atualização: {updatedAt.toLocaleString("pt-BR")}</div>}
{error&&<div style={{marginTop:16,color:"#fca5a5"}}>{error}</div>}

<div className="grid grid3" style={{marginTop:25}}>
  {metricas.map(([label,value,description])=><div className="card" style={cardStyle} key={label}>
    <span className="muted">{label}</span>
    <div style={{fontSize:34,fontWeight:900,marginTop:8}}>{loading?"…":value}</div>
    <div className="muted" style={{fontSize:12,marginTop:7}}>{description}</div>
  </div>)}
</div>

<div className="grid grid2" style={{marginTop:25}}>
  <div className="card" style={cardStyle}>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10}}>
      <div><h2 style={{margin:0,fontSize:20}}>Status das solicitações</h2><p className="muted" style={{margin:"5px 0 0"}}>Distribuição atual</p></div>
      <span className="muted">{rows.length} total</span>
    </div>
    <div style={{marginTop:18,display:"grid",gap:13}}>
      {statusDashboard.map(status=>{
        const total=rows.filter(r=>r.status===status).length;
        const pct=percentual(total,rows.length);
        return <div key={status}>
          <div style={{display:"flex",justifyContent:"space-between",fontSize:13,marginBottom:6}}><span>{status}</span><strong>{total} <span className="muted">({pct}%)</span></strong></div>
          <div style={{height:8,background:"#162b3d",borderRadius:999,overflow:"hidden"}}><div style={{width:pct+"%",height:"100%",background:"#22d3ee",borderRadius:999}}/></div>
        </div>
      })}
    </div>
  </div>

  <div className="card" style={cardStyle}>
    <div><h2 style={{margin:0,fontSize:20}}>Por canal</h2><p className="muted" style={{margin:"5px 0 0"}}>Origem das solicitações</p></div>
    <div style={{marginTop:18,display:"grid",gap:13}}>
      {canais.map(canal=>{
        const total=rows.filter(r=>r.canal===canal).length;
        const pct=percentual(total,rows.length);
        return <div key={canal}>
          <div style={{display:"flex",justifyContent:"space-between",fontSize:13,marginBottom:6}}><span>{canal}</span><strong>{total}</strong></div>
          <div style={{height:8,background:"#162b3d",borderRadius:999,overflow:"hidden"}}><div style={{width:pct+"%",height:"100%",background:"#38bdf8",borderRadius:999}}/></div>
        </div>
      })}
    </div>
  </div>
</div>

<div className="grid grid3" style={{marginTop:25}}>
  <div className="card" style={cardStyle}>
    <h2 style={{margin:0,fontSize:20}}>Prioridades</h2>
    <div style={{marginTop:15}}>
      {PRIORIDADES.map(p=><div key={p} style={{display:"flex",justifyContent:"space-between",padding:"10px 0",borderBottom:"1px solid #1f3548"}}><span>{p}</span><strong>{rows.filter(r=>r.prioridade===p).length}</strong></div>)}
    </div>
  </div>

  <div className="card" style={cardStyle}>
    <h2 style={{margin:0,fontSize:20}}>Categorias</h2>
    <div style={{marginTop:15}}>
      {categorias.length?categorias.slice(0,6).map(c=><div key={c} style={{display:"flex",justifyContent:"space-between",padding:"10px 0",borderBottom:"1px solid #1f3548"}}><span>{c}</span><strong>{rows.filter(r=>r.categoria===c).length}</strong></div>):<p className="muted">Nenhuma categoria registrada.</p>}
    </div>
  </div>

  <div className="card" style={cardStyle}>
    <h2 style={{margin:0,fontSize:20}}>Responsáveis</h2>
    <div style={{marginTop:15}}>
      {responsaveis.length?responsaveis.slice(0,6).map(nome=><div key={nome} style={{display:"flex",justifyContent:"space-between",padding:"10px 0",borderBottom:"1px solid #1f3548"}}><span>{nome}</span><strong>{rows.filter(r=>r.responsavel===nome).length}</strong></div>):<p className="muted">Nenhum responsável atribuído.</p>}
    </div>
  </div>
</div>

<div className="card" style={{padding:20,marginTop:25}}>
  <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:15,flexWrap:"wrap"}}>
    <div><h2 style={{margin:0,fontSize:20}}>Últimas solicitações</h2><p className="muted" style={{margin:"5px 0 0"}}>Entradas mais recentes no sistema</p></div>
    <Link className="btn ghost" to="/atendimentos">Ver todas</Link>
  </div>
  {loading?<p className="muted" style={{marginTop:18}}>Carregando solicitações...</p>:recentes.length===0?<p className="muted" style={{marginTop:18}}>Nenhuma solicitação registrada.</p>:<div style={{overflowX:"auto",marginTop:15}}>
    <table style={{width:"100%",borderCollapse:"collapse"}}>
      <thead><tr>{["Protocolo","Cliente","Assunto","Status","Prioridade","Responsável"].map(h=><th key={h} style={{textAlign:"left",padding:11,borderBottom:"1px solid #29445a",whiteSpace:"nowrap"}}>{h}</th>)}</tr></thead>
      <tbody>{recentes.map(r=><tr key={r.id}>
        {[r.protocolo,r.nome_cliente,r.assunto,r.status,r.prioridade,r.responsavel||"—"].map((v,i)=><td key={i} style={{padding:11,borderBottom:"1px solid #1f3548",whiteSpace:i===2?"normal":"nowrap"}}>{v}</td>)}
      </tr>)}</tbody>
    </table>
  </div>}
</div>

<div className="card" style={{padding:20,marginTop:25}}>
  <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:15,flexWrap:"wrap"}}>
    <div><h2 style={{margin:0,fontSize:20}}>Ações rápidas</h2><p className="muted" style={{margin:"5px 0 0"}}>Acesse os pontos principais da operação.</p></div>
    <div style={{display:"flex",gap:10,flexWrap:"wrap"}}>
      <Link className="btn ghost" to="/atendimentos">Atendimentos</Link>
      <Link className="btn ghost" to="/historico">Histórico</Link>
      <Link className="btn ghost" to="/indicadores">Indicadores</Link>
    </div>
  </div>
</div>
</section>
function Atendimentos(){
const {rows,loading,error,updatedAt,reload}=useSolicitacoes();
const [selected,setSelected]=useState(null),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[historico,setHistorico]=useState([]),[historyLoading,setHistoryLoading]=useState(false),[historyError,setHistoryError]=useState(""),[cancelTarget,setCancelTarget]=useState(null),[deleteTarget,setDeleteTarget]=useState(null),[deleteSheet,setDeleteSheet]=useState(false),[deleting,setDeleting]=useState(false);
const activeRows=rows.filter(r=>r.status!=="Resolvida"&&r.status!=="Cancelada");
const loadHistory=async(id)=>{if(!supabase||!id)return;setHistoryLoading(true);setHistoryError("");const {data,error}=await supabase.from("historico_atendimentos").select("*").eq("solicitacao_id",id).order("criado_em",{ascending:false});if(error)setHistoryError(error.message);else setHistorico(data||[]);setHistoryLoading(false)};
useEffect(()=>{if(selected?.id){loadHistory(selected.id)}else{setHistorico([]);setHistoryError("")}},[selected?.id]);
const update=async()=>{if(!selected||!supabase)return;setSaving(true);setMessage("");const {error}=await supabase.from("solicitacoes").update({status:selected.status,prioridade:selected.prioridade,categoria:selected.categoria||null,responsavel:selected.responsavel||null,resposta:selected.resposta||null,respondido_em:selected.resposta?.trim()?new Date().toISOString():null}).eq("id",selected.id);setSaving(false);if(error){setMessage(error.message);return}setSelected(null);setMessage(selected.status==="Resolvida"?"Atendimento salvo e movido para o Histórico.":"Atendimento atualizado com sucesso.");await reload()};
const cancelar=async()=>{if(!cancelTarget||!supabase)return;setSaving(true);setMessage("");const {error}=await supabase.from("solicitacoes").update({status:"Cancelada"}).eq("id",cancelTarget.id);setSaving(false);if(error){setMessage(error.message);return}setCancelTarget(null);setMessage("Solicitação cancelada e movida para o Histórico.");await reload()};
const remover=async()=>{if(!deleteTarget||!supabase)return;setDeleting(true);setMessage("");const {error}=await supabase.from("solicitacoes").update({excluida:true,excluida_em:new Date().toISOString(),excluir_da_planilha:deleteSheet}).eq("id",deleteTarget.id);setDeleting(false);if(error){setMessage(error.message);return}setDeleteTarget(null);setDeleteSheet(false);setSelected(null);setMessage(deleteSheet?"Solicitação removida do sistema e marcada para exclusão da planilha.":"Solicitação removida do sistema. O registro permanece na planilha.");await reload()};
return <section>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:16}}>
<div><h1>Atendimentos</h1><p className="muted">Aqui ficam somente as solicitações que ainda precisam de atenção.</p></div>
<div style={{textAlign:"right"}}><button className="btn ghost" onClick={reload}>{loading?"Atualizando...":"Atualizar"}</button>{updatedAt&&<div className="muted" style={{fontSize:12,marginTop:6}}>Atualizado às {updatedAt.toLocaleTimeString("pt-BR")}</div>}</div>
</div>
<div className="card" style={{padding:15,marginTop:18,display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><strong>{activeRows.length} pendente{activeRows.length===1?"":"s"}</strong><div className="muted" style={{fontSize:13,marginTop:4}}>Resolvidas e canceladas ficam no Histórico.</div></div><Link className="btn ghost" to="/historico">Ver Histórico →</Link></div>
{(error||message)&&<div style={{marginTop:16,color:error?"#fca5a5":"#86efac"}}>{error||message}</div>}
{loading?<div className="card" style={{padding:25,marginTop:25}}>Carregando solicitações...</div>:<div className="card" style={{padding:14,marginTop:25,overflowX:"auto"}}>
<table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr>{["Protocolo","Cliente","Canal","Assunto","Categoria","Status","Prioridade","Responsável","Ação"].map(h=><th key={h} style={{textAlign:"left",padding:12,borderBottom:"1px solid #29445a",whiteSpace:"nowrap"}}>{h}</th>)}</tr></thead>
<tbody>{activeRows.map(r=><tr key={r.id}>{[r.protocolo,r.nome_cliente,r.canal,r.assunto,r.categoria||"—",r.status,r.prioridade,r.responsavel||"—"].map((v,i)=><td key={i} style={{padding:12,borderBottom:"1px solid #1f3548",whiteSpace:"nowrap"}}>{v}</td>)}<td style={{padding:12,borderBottom:"1px solid #1f3548"}}><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><button className="btn primary" onClick={()=>setSelected({...r})}>Abrir</button><button className="btn ghost" onClick={()=>setCancelTarget(r)}>Cancelar</button><button className="btn ghost" onClick={()=>{setDeleteTarget(r);setDeleteSheet(false)}}>Excluir</button></div></td></tr>)}</tbody></table>
{activeRows.length===0&&<p className="muted" style={{padding:15}}>Nenhuma solicitação pendente. Consulte o Histórico para atendimentos salvos.</p>}
</div>}
{selected&&<div className="card" style={{position:"fixed",inset:0,background:"#061522ee",display:"grid",placeItems:"center",padding:20,zIndex:20}}><div className="card" style={{padding:28,width:"min(700px,100%)",maxHeight:"90vh",overflowY:"auto"}}>
<div style={{display:"flex",justifyContent:"space-between"}}><div><h2 style={{marginTop:0}}>Atendimento {selected.protocolo}</h2><p className="muted">{selected.nome_cliente} · {selected.canal}</p></div><button className="btn ghost" onClick={()=>setSelected(null)}>Fechar</button></div>
<div className="card" style={{padding:16,margin:"18px 0",background:"#0b1e2d"}}><strong>{selected.assunto}</strong><p style={{whiteSpace:"pre-wrap",color:"#cbd5e1"}}>{selected.mensagem}</p></div>
<div><label className="label">Resposta / solução do atendimento</label><textarea className="input" rows="6" value={selected.resposta||""} onChange={e=>setSelected(s=>({...s,resposta:e.target.value}))} placeholder="Digite aqui a resposta ou solução que será registrada neste atendimento..."/></div>
<div className="grid grid2" style={{marginTop:18}}><div><label className="label">Status</label><select className="input" value={selected.status||""} onChange={e=>setSelected(s=>({...s,status:e.target.value}))}>{STATUS.map(x=><option key={x}>{x}</option>)}</select></div><div><label className="label">Prioridade</label><select className="input" value={selected.prioridade||""} onChange={e=>setSelected(s=>({...s,prioridade:e.target.value}))}>{PRIORIDADES.map(x=><option key={x}>{x}</option>)}</select></div><div><label className="label">Categoria</label><input className="input" value={selected.categoria||""} onChange={e=>setSelected(s=>({...s,categoria:e.target.value}))}/></div><div><label className="label">Responsável</label><input className="input" value={selected.responsavel||""} onChange={e=>setSelected(s=>({...s,responsavel:e.target.value}))}/></div></div>
{selected.respondido_em&&<p className="muted" style={{marginTop:15}}>Resposta registrada em {new Date(selected.respondido_em).toLocaleString("pt-BR")}</p>}
<div className="card" style={{padding:18,marginTop:22,background:"#0b1e2d"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12}}><div><h3 style={{margin:0}}>Histórico do atendimento</h3><p className="muted" style={{margin:"6px 0 0"}}>As alterações ficam registradas automaticamente.</p></div><button className="btn ghost" onClick={()=>loadHistory(selected.id)} disabled={historyLoading}>{historyLoading?"Atualizando...":"Atualizar histórico"}</button></div>{historyError&&<div style={{marginTop:14,color:"#fca5a5"}}>{historyError}</div>}{historyLoading&&historico.length===0?<p className="muted" style={{marginTop:18}}>Carregando histórico...</p>:historico.length===0?<p className="muted" style={{marginTop:18}}>Nenhuma alteração registrada ainda.</p>:<div style={{marginTop:18,display:"grid",gap:12}}>{historico.map(h=><div key={h.id} className="card" style={{padding:15}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><strong>{h.acao}</strong><span className="muted" style={{fontSize:12}}>{new Date(h.criado_em).toLocaleString("pt-BR")}</span></div>{h.status_anterior!==h.status_novo&&<div style={{marginTop:9}}><span className="muted">Status:</span> {h.status_anterior||"—"} → <strong>{h.status_novo||"—"}</strong></div>}{h.prioridade_anterior!==h.prioridade_nova&&<div style={{marginTop:7}}><span className="muted">Prioridade:</span> {h.prioridade_anterior||"—"} → <strong>{h.prioridade_nova||"—"}</strong></div>}{h.categoria_anterior!==h.categoria_nova&&<div style={{marginTop:7}}><span className="muted">Categoria:</span> {h.categoria_anterior||"—"} → <strong>{h.categoria_nova||"—"}</strong></div>}{h.responsavel_anterior!==h.responsavel_novo&&<div style={{marginTop:7}}><span className="muted">Responsável:</span> {h.responsavel_anterior||"—"} → <strong>{h.responsavel_novo||"—"}</strong></div>}{h.resposta&&<div style={{marginTop:10,paddingTop:10,borderTop:"1px solid #1f3548"}}><span className="muted">Resposta registrada:</span><p style={{whiteSpace:"pre-wrap",margin:"6px 0 0"}}>{h.resposta}</p></div>}</div>)}</div>}</div>
{message&&<div style={{marginTop:15,color:"#fca5a5"}}>{message}</div>}
<div style={{display:"grid",gap:10,marginTop:20}}><button className="btn primary" disabled={saving} onClick={update}>{saving?"Salvando...":"Salvar atendimento"}</button><button className="btn ghost" disabled={saving} onClick={()=>setCancelTarget(selected)}>Cancelar solicitação</button><button className="btn ghost" disabled={saving} onClick={()=>{setDeleteTarget(selected);setDeleteSheet(false)}}>Excluir solicitação</button></div>
</div></div>}
{cancelTarget&&<div className="card" style={{position:"fixed",inset:0,background:"#061522ee",display:"grid",placeItems:"center",padding:20,zIndex:30}}><div className="card" style={{padding:28,width:"min(500px,100%)"}}><h2 style={{marginTop:0}}>Cancelar solicitação?</h2><p className="muted">O protocolo <strong>{cancelTarget.protocolo}</strong> será marcado como Cancelada e sairá de Atendimentos para o Histórico.</p><div style={{display:"flex",gap:10,justifyContent:"flex-end",flexWrap:"wrap",marginTop:20}}><button className="btn ghost" onClick={()=>setCancelTarget(null)}>Voltar</button><button className="btn primary" disabled={saving} onClick={cancelar}>{saving?"Cancelando...":"Confirmar cancelamento"}</button></div></div></div>}
{deleteTarget&&<div className="card" style={{position:"fixed",inset:0,background:"#061522ee",display:"grid",placeItems:"center",padding:20,zIndex:30}}><div className="card" style={{padding:28,width:"min(560px,100%)"}}><h2 style={{marginTop:0}}>Remover solicitação?</h2><p className="muted">Protocolo <strong>{deleteTarget.protocolo}</strong>. Escolha onde deseja remover.</p><label style={{display:"flex",gap:10,alignItems:"flex-start",marginTop:18,cursor:"pointer"}}><input type="radio" checked={!deleteSheet} onChange={()=>setDeleteSheet(false)}/><span><strong>Somente do sistema</strong><br/><span className="muted">Sai do site/atendimento, mas permanece na planilha e no banco para histórico.</span></span></label><label style={{display:"flex",gap:10,alignItems:"flex-start",marginTop:14,cursor:"pointer"}}><input type="radio" checked={deleteSheet} onChange={()=>setDeleteSheet(true)}/><span><strong>Do sistema e da planilha</strong><br/><span className="muted">Sai do atendimento e o webhook marcará a linha da planilha para remoção.</span></span></label><div className="card" style={{padding:14,marginTop:18,background:"#0b1e2d"}}><span className="muted" style={{fontSize:13}}>O histórico do atendimento não é apagado.</span></div><div style={{display:"flex",gap:10,justifyContent:"flex-end",flexWrap:"wrap",marginTop:20}}><button className="btn ghost" onClick={()=>{setDeleteTarget(null);setDeleteSheet(false)}}>Voltar</button><button className="btn primary" disabled={deleting} onClick={remover}>{deleting?"Removendo...":"Confirmar remoção"}</button></div></div></div>}
</section>
}
function Historico(){
const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[updatedAt,setUpdatedAt]=useState(null),[selected,setSelected]=useState(null),[deleteTarget,setDeleteTarget]=useState(null),[deleteSheet,setDeleteSheet]=useState(false),[deleting,setDeleting]=useState(false);
const load=async()=>{if(!supabase){setError("Supabase não configurado.");setLoading(false);return}setLoading(true);const {data,error}=await supabase.from("solicitacoes").select("*").eq("excluida",false).in("status",["Resolvida","Cancelada"]).order("created_at",{ascending:false});if(error)setError(error.message);else{setRows(data||[]);setUpdatedAt(new Date())}setLoading(false)};useEffect(()=>{load()},[]);
const remover=async()=>{if(!deleteTarget||!supabase)return;setDeleting(true);setError("");const {error}=await supabase.from("solicitacoes").update({excluida:true,excluida_em:new Date().toISOString(),excluir_da_planilha:deleteSheet}).eq("id",deleteTarget.id);setDeleting(false);if(error){setError(error.message);return}setDeleteTarget(null);setDeleteSheet(false);setSelected(null);await load()};
return <section><div style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:16}}><div><h1>Histórico de atendimentos</h1><p className="muted">Atendimentos já salvos, resolvidos ou cancelados, separados da fila principal.</p></div><div style={{textAlign:"right"}}><button className="btn ghost" onClick={load}>{loading?"Atualizando...":"Atualizar"}</button>{updatedAt&&<div className="muted" style={{fontSize:12,marginTop:6}}>Atualizado às {updatedAt.toLocaleTimeString("pt-BR")}</div>}</div></div>{error&&<div style={{marginTop:16,color:"#fca5a5"}}>{error}</div>}<div className="card" style={{padding:14,marginTop:25,overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr>{["Protocolo","Cliente","Assunto","Status","Responsável","Resposta","Ação"].map(h=><th key={h} style={{textAlign:"left",padding:12,borderBottom:"1px solid #29445a",whiteSpace:"nowrap"}}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td style={{padding:12,borderBottom:"1px solid #1f3548",whiteSpace:"nowrap"}}>{r.protocolo}</td><td style={{padding:12,borderBottom:"1px solid #1f3548",whiteSpace:"nowrap"}}>{r.nome_cliente}</td><td style={{padding:12,borderBottom:"1px solid #1f3548"}}>{r.assunto}</td><td style={{padding:12,borderBottom:"1px solid #1f3548",whiteSpace:"nowrap"}}>{r.status}</td><td style={{padding:12,borderBottom:"1px solid #1f3548",whiteSpace:"nowrap"}}>{r.responsavel||"—"}</td><td style={{padding:12,borderBottom:"1px solid #1f3548",maxWidth:300}}>{r.resposta?<span title={r.resposta}>{r.resposta.length>70?r.resposta.slice(0,70)+"…":r.resposta}</span>:"—"}</td><td style={{padding:12,borderBottom:"1px solid #1f3548"}}><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><button className="btn primary" onClick={()=>setSelected(r)}>Ver</button><button className="btn ghost" onClick={()=>{setDeleteTarget(r);setDeleteSheet(false)}}>Excluir</button></div></td></tr>)}</tbody></table>{loading&&<p className="muted" style={{padding:15}}>Carregando histórico...</p>}{!loading&&rows.length===0&&<p className="muted" style={{padding:15}}>Nenhum atendimento salvo ainda.</p>}</div>
{selected&&<div className="card" style={{position:"fixed",inset:0,background:"#061522ee",display:"grid",placeItems:"center",padding:20,zIndex:20}}><div className="card" style={{padding:28,width:"min(650px,100%)",maxHeight:"90vh",overflowY:"auto"}}><div style={{display:"flex",justifyContent:"space-between",gap:15}}><div><h2 style={{marginTop:0}}>Histórico {selected.protocolo}</h2><p className="muted">{selected.nome_cliente} · {selected.status}</p></div><button className="btn ghost" onClick={()=>setSelected(null)}>Fechar</button></div><div className="card" style={{padding:18,marginTop:18,background:"#0b1e2d"}}><p className="muted">Assunto</p><strong>{selected.assunto}</strong><p className="muted" style={{marginTop:15}}>Solicitação</p><p style={{whiteSpace:"pre-wrap"}}>{selected.mensagem}</p><p className="muted" style={{marginTop:15}}>Resposta / solução</p><p style={{whiteSpace:"pre-wrap"}}>{selected.resposta||"Sem resposta registrada."}</p><p className="muted" style={{marginTop:15}}>Responsável</p><strong>{selected.responsavel||"—"}</strong></div><p className="muted" style={{fontSize:13,marginTop:18}}>A edição de atendimentos já salvos pode ser adicionada como próxima etapa sem retirar este histórico.</p></div></div>}
{deleteTarget&&<div className="card" style={{position:"fixed",inset:0,background:"#061522ee",display:"grid",placeItems:"center",padding:20,zIndex:30}}><div className="card" style={{padding:28,width:"min(560px,100%)"}}><h2 style={{marginTop:0}}>Remover do Histórico?</h2><p className="muted">Protocolo <strong>{deleteTarget.protocolo}</strong>. Escolha onde deseja remover.</p><label style={{display:"flex",gap:10,alignItems:"flex-start",marginTop:18,cursor:"pointer"}}><input type="radio" checked={!deleteSheet} onChange={()=>setDeleteSheet(false)}/><span><strong>Somente do sistema</strong><br/><span className="muted">O registro some do site, mas permanece na planilha.</span></span></label><label style={{display:"flex",gap:10,alignItems:"flex-start",marginTop:14,cursor:"pointer"}}><input type="radio" checked={deleteSheet} onChange={()=>setDeleteSheet(true)}/><span><strong>Do sistema e da planilha</strong><br/><span className="muted">O webhook também remove a linha correspondente da planilha.</span></span></label><div className="card" style={{padding:14,marginTop:18,background:"#0b1e2d"}}><span className="muted" style={{fontSize:13}}>O histórico detalhado permanece na base para auditoria.</span></div><div style={{display:"flex",gap:10,justifyContent:"flex-end",marginTop:20}}><button className="btn ghost" onClick={()=>{setDeleteTarget(null);setDeleteSheet(false)}}>Voltar</button><button className="btn primary" disabled={deleting} onClick={remover}>{deleting?"Removendo...":"Confirmar remoção"}</button></div></div></div>}
</section>
}

function Indicadores(){const {rows,loading,error,updatedAt,reload}=useSolicitacoes();const categorias=[...new Set(rows.map(r=>r.categoria).filter(Boolean))].sort();return <section><div style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:16}}><div><h1>Indicadores</h1><p className="muted">Indicadores gerenciais calculados diretamente das solicitações.</p></div><div style={{textAlign:"right"}}><button className="btn ghost" onClick={reload}>{loading?"Atualizando...":"Atualizar"}</button>{updatedAt&&<div className="muted" style={{fontSize:12,marginTop:6}}>Atualizado às {updatedAt.toLocaleTimeString("pt-BR")}</div>}</div></div>{error&&<div style={{marginTop:16,color:"#fca5a5"}}>{error}</div>}<div className="grid grid4" style={{marginTop:25}}>{[["Total",rows.length],["Pendentes",rows.filter(r=>r.status!=="Resolvida"&&r.status!=="Cancelada").length],["Urgentes",rows.filter(r=>r.prioridade==="Urgente").length],["Resolvidas",rows.filter(r=>r.status==="Resolvida").length]].map(([x,n])=><div className="card" style={cardStyle} key={x}><span className="muted">{x}</span><div style={{fontSize:34,fontWeight:900,marginTop:8}}>{loading?"…":n}</div></div>)}</div><div className="grid grid2" style={{marginTop:25}}><div className="card" style={cardStyle}><h3>Distribuição por status</h3>{STATUS.map(s=><div key={s} style={{display:"flex",justifyContent:"space-between",padding:"10px 0",borderBottom:"1px solid #1f3548"}}><span>{s}</span><b>{rows.filter(r=>r.status===s).length}</b></div>)}</div><div className="card" style={cardStyle}><h3>Distribuição por categoria</h3>{categorias.length?categorias.map(c=><div key={c} style={{display:"flex",justifyContent:"space-between",padding:"10px 0",borderBottom:"1px solid #1f3548"}}><span>{c}</span><b>{rows.filter(r=>r.categoria===c).length}</b></div>):<p className="muted">As categorias aparecerão conforme novas solicitações forem registradas.</p>}</div></div><div className="card" style={{padding:20,marginTop:25}}><strong>Power BI / Copilot</strong><p className="muted">Esta área já possui os dados-base. A incorporação do relatório Power BI poderá ser feita sem substituir estes indicadores.</p></div></section>}

function Configuracoes(){const {rows}=useSolicitacoes();const [tab,setTab]=useState("usuarios");const [responsavel,setResponsavel]=useState(localStorage.getItem("conecta_responsavel")||"");const [auto,setAuto]=useState(localStorage.getItem("conecta_auto")!=="false");const [saved,setSaved]=useState("");const categorias=[...new Set(rows.map(r=>r.categoria).filter(Boolean))].sort();const save=()=>{localStorage.setItem("conecta_responsavel",responsavel);localStorage.setItem("conecta_auto",String(auto));setSaved("Configurações salvas neste navegador.");setTimeout(()=>setSaved(""),2500)};const tabs=[["usuarios","Usuários e equipes"],["categorias","Categorias"],["ia","Regras da IA"],["automacoes","Automações"]];return <section><h1>Configurações</h1><p className="muted">Configurações operacionais do Conecta Mais.</p><div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:25}}>{tabs.map(([id,label])=><button key={id} className={tab===id?"btn primary":"btn ghost"} onClick={()=>setTab(id)}>{label}</button>)}</div><div className="card" style={{padding:25,marginTop:20}}>{tab==="usuarios"&&<><h2>Usuários e equipes</h2><p className="muted">Defina o responsável padrão para os atendimentos.</p><label className="label">Responsável padrão</label><input className="input" value={responsavel} onChange={e=>setResponsavel(e.target.value)} placeholder="Nome do responsável"/><button className="btn primary" style={{marginTop:15}} onClick={save}>Salvar configuração</button></>}{tab==="categorias"&&<><h2>Categorias utilizadas</h2><p className="muted">Lista formada automaticamente a partir das solicitações registradas.</p>{categorias.length?<div style={{display:"flex",gap:10,flexWrap:"wrap"}}>{categorias.map(c=><span key={c} className="card" style={{padding:"9px 14px"}}>{c}</span>)}</div>:<p className="muted">Nenhuma categoria cadastrada ainda.</p>}</>}{tab==="ia"&&<><h2>Regras da IA</h2><p className="muted">Preparação operacional para classificação e automação futura.</p><label style={{display:"flex",gap:10,alignItems:"center",marginTop:18}}><input type="checkbox" defaultChecked/> Sugerir categoria a partir da mensagem</label><label style={{display:"flex",gap:10,alignItems:"center",marginTop:14}}><input type="checkbox" defaultChecked/> Sugerir prioridade a partir da mensagem</label><p className="muted" style={{marginTop:20}}>As sugestões poderão ser conectadas a um agente de IA na próxima etapa.</p></>}{tab==="automacoes"&&<><h2>Automações</h2><p className="muted">Controles básicos para o fluxo operacional.</p><label style={{display:"flex",gap:10,alignItems:"center",marginTop:18}}><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/> Ativar automações do atendimento</label><button className="btn primary" style={{marginTop:15}} onClick={save}>Salvar configuração</button></>}{saved&&<div style={{marginTop:15,color:"#86efac"}}>{saved}</div>}</div></section>}

function App(){return <Routes><Route path="/" element={<Home/>}/><Route path="/solicitacao" element={<Solicitacao/>}/><Route path="/acompanhar" element={<Acompanhar/>}/><Route path="/protocolo/:id" element={<Protocolo/>}/><Route path="/login" element={<Login/>}/><Route element={<Protected/>}><Route element={<Internal/>}><Route path="/dashboard" element={<Dashboard/>}/><Route path="/atendimentos" element={<Atendimentos/>}/><Route path="/historico" element={<Historico/>}/><Route path="/indicadores" element={<Indicadores/>}/><Route path="/configuracoes" element={<Configuracoes/>}/></Route></Route><Route path="*" element={<Navigate to="/" replace/>}/></Routes>}
ReactDOM.createRoot(document.getElementById("root")).render(<BrowserRouter><App/></BrowserRouter>);
