create table if not exists public.solicitacoes (
  id bigint generated by default as identity primary key,
  protocolo text unique not null,
  nome_cliente text not null,
  canal text not null,
  assunto text not null,
  mensagem text not null,
  categoria text,
  status text not null default 'Aberta',
  prioridade text not null default 'Normal',
  responsavel text,
  resposta text,
  respondido_em timestamptz,
  created_at timestamptz not null default now()
);

alter table public.solicitacoes add column if not exists resposta text;
alter table public.solicitacoes add column if not exists respondido_em timestamptz;

alter table public.solicitacoes enable row level security;

drop policy if exists "public can create solicitacoes" on public.solicitacoes;
create policy "public can create solicitacoes" on public.solicitacoes for insert to anon, authenticated with check (true);

drop policy if exists "authenticated can read solicitacoes" on public.solicitacoes;
create policy "authenticated can read solicitacoes" on public.solicitacoes for select to authenticated using (true);

drop policy if exists "authenticated can update solicitacoes" on public.solicitacoes;
create policy "authenticated can update solicitacoes" on public.solicitacoes for update to authenticated using (true) with check (true);
