-- Histórico do atendimento
-- Execute este arquivo no Supabase > SQL Editor.

create table if not exists public.historico_atendimentos (
  id bigint generated by default as identity primary key,
  solicitacao_id bigint not null references public.solicitacoes(id) on delete cascade,
  protocolo text not null,
  acao text not null,
  status_anterior text,
  status_novo text,
  prioridade_anterior text,
  prioridade_nova text,
  categoria_anterior text,
  categoria_nova text,
  responsavel_anterior text,
  responsavel_novo text,
  resposta text,
  criado_em timestamptz not null default now(),
  criado_por uuid references auth.users(id)
);

alter table public.historico_atendimentos enable row level security;

drop policy if exists "authenticated can read historico_atendimentos" on public.historico_atendimentos;
create policy "authenticated can read historico_atendimentos"
on public.historico_atendimentos
for select
to authenticated
using (true);

drop policy if exists "authenticated can create historico_atendimentos" on public.historico_atendimentos;
create policy "authenticated can create historico_atendimentos"
on public.historico_atendimentos
for insert
to authenticated
with check (true);

create or replace function public.registrar_historico_solicitacao()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if (old.status is distinct from new.status)
     or (old.prioridade is distinct from new.prioridade)
     or (old.categoria is distinct from new.categoria)
     or (old.responsavel is distinct from new.responsavel)
     or (old.resposta is distinct from new.resposta) then
    insert into public.historico_atendimentos (
      solicitacao_id, protocolo, acao,
      status_anterior, status_novo,
      prioridade_anterior, prioridade_nova,
      categoria_anterior, categoria_nova,
      responsavel_anterior, responsavel_novo,
      resposta, criado_por
    ) values (
      new.id, new.protocolo, 'Atualização do atendimento',
      old.status, new.status,
      old.prioridade, new.prioridade,
      old.categoria, new.categoria,
      old.responsavel, new.responsavel,
      new.resposta, auth.uid()
    );
  end if;
  return new;
end;
$$;

drop trigger if exists trg_historico_solicitacao on public.solicitacoes;
create trigger trg_historico_solicitacao
after update on public.solicitacoes
for each row
execute function public.registrar_historico_solicitacao();

notify pgrst, 'reload schema';
